### ISSUE TITLE
Compile error: Compile stage2 and stage3 differently differs

### ISSUE THREAD

**Issue by RevySR** [XUANTIE-RV/gcc#1]
Comparing stages 2 and 3
warning: gcc/SYSTEM.o differs
warning: gcc/cc1obj-checksum.o differs
warning: gcc/m2/gm2-compiler-boot/M2Version.o differs
warning: gcc/cc1objplus-checksum.o differs
Bootstrap comparison failure!
gcc/ira-color.o differs
gcc/expr.o differs
gcc/ipa-fnsummary.o differs
gcc/cselib.o differs
gcc/gimplify.o differs
gcc/lra-remat.o differs
gcc/cse.o differs
gcc/tree-switch-conversion.o differs
gcc/loop-invariant.o differs
gcc/tree-ssa-reassoc.o differs
gcc/ada/adaint.o differs
gcc/ada/osint.o differs
gcc/ada/set_targ.o differs
gcc/ada/osint-c.o differs
gcc/ada/sem_util.o differs
gcc/ada/sem_attr.o differs
gcc/ada/switch-c.o differs
gcc/ada/prep.o differs
gcc/ada/prepcomp.o differs
gcc/ada/switch.o differs
gcc/ada/bindgen.o differs
gcc/ada/libgnat/s-strcom.o differs
gcc/ada/libgnat/s-carun8.o differs
gcc/ada/libgnat/s-os_lib.o differs
gcc/ada/frontend.o differs
gcc/ada/osint-b.o differs
gcc/riscv.o differs
gcc/d/dmacro.o differs
gcc/hsa-gen.o differs
gcc/modulo-sched.o differs
gcc/c-family/c-pragma.o differs
gcc/sched-rgn.o differs
gcc/tree-ssa-coalesce.o differs
gcc/tree-ssa-structalias.o differs
gcc/analyzer/program-state.o differs
gcc/analyzer/region-model.o differs
gcc/analyzer/diagnostic-manager.o differs
gcc/analyzer/constraint-manager.o differs
gcc/recog.o differs
gcc/gimple-ssa-strength-reduction.o differs
gcc/regrename.o differs
gcc/tree-into-ssa.o differs
gcc/gcse.o differs
gcc/tree-ssa-live.o differs
gcc/emit-rtl.o differs
gcc/dse.o differs
gcc/tree-phinodes.o differs
gcc/ira-costs.o differs
gcc/tree-diagnostic-path.o differs
gcc/gimple-fold.o differs
gcc/fortran/simplify.o differs
gcc/stor-layout.o differs
gcc/ipa-cp.o differs
gcc/optabs.o differs
gcc/lto-cgraph.o differs
gcc/ira.o differs
gcc/function.o differs
gcc/combine.o differs
gcc/ddg.o differs
gcc/diagnostic-show-locus.o differs
gcc/go/statements.o differs
gcc/omp-simd-clone.o differs
gcc/builtins.o differs
gcc/build/genextract.o differs
gcc/build/genautomata.o differs
gcc/sel-sched.o differs
gcc/ira-lives.o differs
gcc/reginfo.o differs
gcc/m2/stor-layout.o differs
gcc/m2/gm2-compiler-boot/M2Base.o differs
gcc/m2/gm2-compiler-boot/M2ALU.o differs
gcc/dwarf2out.o differs
libdecnumber/decNumber.o differs
libiberty/pic/dyn-string.o differs
make[4]: *** [Makefile:25636: compare] Error 1

full log:
https://fars.ee/Kiba

debian source:
https://github.com/revyos/gcc-10-10.4.0/tree/dev

**Comment by Cooper-Qu** [comment]
https://github.com/T-head-Semi/gcc/commit/fc57a6b029138a64c8312f4cf93cf5ffd20db45d
https://github.com/T-head-Semi/gcc/commit/edcf8e2f2ad80dd93423af1e29c04b9fe6d42bae

Fixed.
