### ISSUE TITLE
jpeg-xl: 编译测试发生src/tcmalloc.cc Attempt to free invalid pointer 0xa3fdffffa3fbffff

### ISSUE THREAD

**Issue by RevySR** [XUANTIE-RV/gcc#12]
前置环境配置:

https://github.com/revyos/revyos/wiki/Debian-%E8%BD%AF%E4%BB%B6%E5%8C%85%E6%9E%84%E5%BB%BA%E6%B5%81%E7%A8%8B

复现步骤：

sg2042: 可复现
qemu-user: 可复现
lpi4a: 可复现

```
mkdir jpeg-xl && cd jpeg-xl
dget -d https://deb.debian.org/debian/pool/main/j/jpeg-xl/jpeg-xl_0.7.0-10.dsc

sbuild --arch=riscv64 -d sid -c sid-riscv64-revyos-c910v-sbuild jpeg-xl_0.7.0-10.dsc

```

```
FAILED: lib/tests/color_management_test lib/color_management_test[1]_tests.cmake /<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/lib/color_management_test[1]_tests.cmake
: && /usr/bin/c++ -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DJXL_DEBUG_WARNING -DJXL_DEBUG_ON_ERROR -Wdate-time -D_FORTIFY_SOURCE=2 -fno-rtti -funwind-tables -fno-omit-frame-pointer -Wl,-z,relro     -fPIE -pie lib/CMakeFiles/color_management_test.dir/jxl/color_management_test.cc.o -o lib/tests/color_management_test  tools/box/libbox.a  lib/libjxl_extras-static.a  lib/libjxl_testlib-static.a  -lgmock  lib/libjxl_threads.a  /usr/lib/riscv64-linux-gnu/libjpeg.so  /usr/lib/riscv64-linux-gnu/libpng.so  /usr/lib/riscv64-linux-gnu/libz.so  /usr/lib/riscv64-linux-gnu/libOpenEXR-3_1.so  /usr/lib/riscv64-linux-gnu/libOpenEXRUtil-3_1.so  /usr/lib/riscv64-linux-gnu/libOpenEXRCore-3_1.so  /usr/lib/riscv64-linux-gnu/libIex-3_1.so  /usr/lib/riscv64-linux-gnu/libIlmThread-3_1.so  /usr/lib/riscv64-linux-gnu/libImath-3_1.so  lib/libjxl.a  /usr/lib/riscv64-linux-gnu/libbrotlidec.so  /usr/lib/riscv64-linux-gnu/libbrotlicommon.so  /usr/lib/riscv64-linux-gnu/libbrotlienc.so  /usr/lib/riscv64-linux-gnu/liblcms2.so  /usr/lib/riscv64-linux-gnu/libtcmalloc_minimal.so  /usr/lib/riscv64-linux-gnu/libhwy.so  /usr/lib/riscv64-linux-gnu/libgtest_main.a  /usr/lib/riscv64-linux-gnu/libgtest.a && cd /<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/lib && /usr/bin/cmake -D TEST_TARGET=color_management_test -D TEST_EXECUTABLE=/<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/lib/tests/color_management_test -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/lib -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=color_management_test_TESTS -D CTEST_FILE=/<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/lib/color_management_test[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=240 -D TEST_XML_OUTPUT_DIR= -P /usr/share/cmake-3.25/Modules/GoogleTestAddTests.cmake
src/tcmalloc.cc:333] Attempt to free invalid pointer 0xa3fdffffa3fbffff
CMake Error at /usr/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/lib/tests/color_management_test'
    Result: Subprocess aborted
    Output:


Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)
```

full log:
[jpeg-xl_0.7.0-10_riscv64.build.log](https://github.com/T-head-Semi/gcc/files/12515225/jpeg-xl_0.7.0-10_riscv64.build.log)

**Comment by RevySR** [comment]
gcc-13 on sg2042: pass

**Comment by Cookfeces** [comment]
首先，编译jpeg-xl时，会执行测试程序lib/tests/color_management_test，发生"src/tcmalloc.cc Attempt to free invalid pointer 0xa3fdffffa3fbffff "错误的lib/tests/color_management_test测试程序，而并非编译命令。

然后，缩小错误排查范围，将编译cache_aligned.cc文件的选项中去掉vector(比如-march=rv64gc)，程序执行通过；加上vector(比如-march=rv64gcv0p7)，则程序会执行出错。即使关闭优化-O0，加vector也会出错。

查看cache_aligned.cc，加和不加vector唯一的影响是：
`
struct AllocationHeader {
  void* allocated;
  size_t allocated_size;
  uint8_t left_padding[hwy::kMaxVectorSize];
};
`
hwy::kMaxVectorSize来自于/usr/include/hwy/base.h，
`
//------------------------------------------------------------------------------                                                                                                                                                                                         
// kMaxVectorSize (undocumented, pending removal)                                                                                                                                                                                                                        

#if HWY_ARCH_X86
static constexpr HWY_MAYBE_UNUSED size_t kMaxVectorSize = 64;  // AVX-512                                                                                                                                                                                                
#elif HWY_ARCH_RVV && defined(__riscv_vector)                                                                                                                                                                                                                            
// Not actually an upper bound on the size.                                                                                                                                                                                                                              
static constexpr HWY_MAYBE_UNUSED size_t kMaxVectorSize = 4096;                                                                                                                                                                                                          
#else
static constexpr HWY_MAYBE_UNUSED size_t kMaxVectorSize = 16;                                                                                                                                                                                                            
#endif 
`

继续查看cache_aligned.cc的代码，发现jpeg-xl对RVV的适配代码只有https://github.com/libjxl/libjxl/commit/c5207e041e834b7a71440f12eef808501236bf42

根据上述的分析，可以基本上排除编译的问题（加不加vector的返回编也只有left_padding的size区别，并没有逻辑上的不一致），而是jpeg-xl对RVV的适配存在BUG

**Comment by Cooper-Qu** [comment]
首先，编译jpeg-xl时，会执行测试程序lib/tests/color_management_test，发生"src/tcmalloc.cc Attempt to free invalid pointer 0xa3fdffffa3fbffff "错误的lib/tests/color_management_test测试程序，而并非编译命令。

然后，缩小错误排查范围，将编译cache_aligned.cc文件的选项中去掉vector(比如-march=rv64gc)，程序执行通过；加上vector(比如-march=rv64gcv0p7)，则程序会执行出错。即使关闭优化-O0，加vector也会出错。

查看cache_aligned.cc，加和不加vector唯一的影响是：
```
struct AllocationHeader {
  void* allocated;
  size_t allocated_size;
  uint8_t left_padding[hwy::kMaxVectorSize];
};
```
hwy::kMaxVectorSize来自于/usr/include/hwy/base.h，
```
//------------------------------------------------------------------------------                                                                                                                                                                                         
// kMaxVectorSize (undocumented, pending removal)                                                                                                                                                                                                                        

#if HWY_ARCH_X86
static constexpr HWY_MAYBE_UNUSED size_t kMaxVectorSize = 64;  // AVX-512                                                                                                                                                                                                
#elif HWY_ARCH_RVV && defined(__riscv_vector)                                                                                                                                                                                                                            
// Not actually an upper bound on the size.                                                                                                                                                                                                                              
static constexpr HWY_MAYBE_UNUSED size_t kMaxVectorSize = 4096;                                                                                                                                                                                                          
#else
static constexpr HWY_MAYBE_UNUSED size_t kMaxVectorSize = 16;                                                                                                                                                                                                            
#endif 
```

继续查看cache_aligned.cc的代码，发现jpeg-xl对RVV的适配代码只有https://github.com/libjxl/libjxl/commit/c5207e041e834b7a71440f12eef808501236bf42

根据上述的分析，可以基本上排除编译的问题（加不加vector的反汇编也只有left_padding的size区别，并没有逻辑上的不一致），而是jpeg-xl对RVV的适配存在BUG

**Comment by RevySR** [comment]
RVV引用 `highway` 代码 

`highway` 新版本头文件识别改成识别 `__riscv_v_intrinsic ` macro 
与 `xtheadv` 已经分开
`jpeg-xl` 与 `highway` 升级版本后解决问题
