### ISSUE TITLE
openblas: zblat2 test timeout 

### ISSUE THREAD

**Issue by RevySR** [XUANTIE-RV/gcc#2]
https://github.com/xianyi/OpenBLAS/issues/4098

OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat2 < ./sblat2.dat
timeout

In Debian CORE=C910V & thead gcc:

| CFLAGS | FFLAGS | result |
| :--: | :--: | :--: |
| O2 | O2 | ❌ Timeout |
| O2 | O1 | ❌ Timeout |
| O1 | O2 | ✅ Passed |
| O1 | O1 | ✅ Passed |

**Comment by Cooper-Qu** [comment]
The code generation here is not the problem. The issue with the code combined with QEMU's behavior caused the inconsistency between O1 and O2 options. More detailed information can be found in https://github.com/xianyi/OpenBLAS/issues/4098#issuecomment-1609513618
