### ISSUE TITLE
[gcc-10] Bad code generation for Vector Mask-Register Logical Operations.

### ISSUE THREAD

**Issue by RevySR** [XUANTIE-RV/gcc#9]
https://github.com/revyos/revyos/issues/16

**Comment by Cookfeces** [comment]
As comment in 
https://github.com/revyos/revyos/issues/16#issuecomment-1691059403

The vtype needs to be set for the Vector Mask-Register Logical Operations.

**Comment by Cooper-Qu** [comment]
As comment in https://github.com/revyos/revyos/issues/16#issuecomment-1691059403

The vtype needs to be set for the Vector Mask-Register Logical Operations.
